spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/
  instance:
    hostname: localhost
server:
  port: 8761
